### ISSUE TITLE
 UI Issues: Dark Mode Icon Misalignment, Missing Footer, and Small Text in "About Us" and "Feature Post"

### ISSUE THREAD

**Issue by Kavish-Paraswar** [ANSHIKA-26/WordWise#1162]
The dark mode icons and the circle are slightly out of the small container, causing misalignment.
![image](https://github.com/user-attachments/assets/96d393a1-34cc-494b-9265-943b706bf25d)

The webpage is missing a footer section. 
![image](https://github.com/user-attachments/assets/d62549e9-59c8-47ad-88e6-b7d4248200bf)

The text in the "About Us" and "Feature Post" sections is too small, reducing readability. The font size should be increased to enhance the user experience.
![image](https://github.com/user-attachments/assets/1cdde0f5-4255-4ea4-8352-5f44789b0f21)

With my strong background in HTML, CSS, and JavaScript, and considering the nature of the work required, I believe this task should be assigned as Level 2 or Level 3. Please assign this under GSoC '24 and Hacktoberfest.

**Comment by ANSHIKA-26** [comment]
there are separate issues for every point you have mentioned in this issue !

**Comment by ANSHIKA-26** [comment]
dark mode icons already fixed

**Comment by ANSHIKA-26** [comment]
I'm closing this issue because all points you've raised already exist as separate issues. This is unacceptable—you were clearly supposed to check for existing issues before creating a new one. Please follow the guidelines and make sure you do a proper check next time to avoid wasting time and cluttering the repository
