### ISSUE TITLE
Input value UI of FAQ page

### ISSUE THREAD

**Issue by rahulbamnuya** [ANSHIKA-26/WordWise#1258]
![Screenshot_2024-10-21-15-31-06-71_439a3fec0400f8974d35eed09a31f914.jpg](https://github.com/user-attachments/assets/d46f467b-e075-407d-a754-1fc432d8f3bf)

**Comment by ANSHIKA-26** [comment]
@rahulbamnuya , the UI is already in good shape, and another issue for the same exists. You’ve spammed 5 issues related to the UI of different sections, but none of them have any information on how you actually plan to improve it.

Please explain the changes you wish to make in the open issues. This isn’t the right way to open issues—each one should provide a full explanation of the problem and how you intend to solve it.

Also, since I’ve already assigned one issue to you, kindly focus on that, make a PR, and only then consider opening additional issues.
