### ISSUE TITLE
REVIEW SECTION

### ISSUE THREAD

**Issue by Meetpidev** [ANSHIKA-26/WordWise#1778]
**Is your feature request related to a problem? Please describe.**
YES

**Describe the solution you'd like**
WE SHOULD ADD REVIEW SECTION IN BLOG WHERE USER CAN POST THEIR REVIEW..

**Describe alternatives you've considered**
OR AS OF NOW WE CAN PUT DUMMY REVIEWS SECTION GIVEN BY USERS.... LATER ON WE CAN DO BACKEND FUNCTIONALITY

**Comment by ANSHIKA-26** [comment]
blogging website , we do not need reviews @Meetpidev kindly stop spamming of issues i believe in a span of 10-15 minutes you have raised 5 issues out of which i have assigned some to you , kindly work on them , make a PR and then resume making issues , this will help ,
 also if you still wish to make issues go through the closed issues section  briefly to look at what issues i have closed since they are not needed  , you are basically repeating a lot of old closed issues , this might save you the trouble of creating an issue which might get closed in future !

**Comment by ANSHIKA-26** [comment]
regardless of that , if you still believe you have an important issue to raise go ahead , kindly follow issue template and add required explanations , we are planning to migrate to MERN app and the backend and frontend is already there, you are welcome to add more routes and features !
