### ISSUE TITLE
implement Backend for discussion forum 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ANSHIKA-26/WordWise#1786]
i can build the backend for discussion forum 
 where i effieciently save the data of question and answer in database
 
 and ALSO retreview the data and showcase on our discussion page 
also take care of answered and unanswered question

**Comment by ANSHIKA-26** [comment]
@Sawan-Kushwah some things i would like to point out -
1. after your PR is merge , kindly close the issue as well or use the format fixes#issuenumber in the pr description so that the issue is closed after PR is merged
2. please dont ask for upgradation of level labels , if you think that low label has been assigned then kindly ask the same on issue , not on PR so that issue and PR have same level labels
thanks

**Comment by Sawan-Kushwah** [comment]
@ANSHIKA-26 CAN I GET level 3 as i implemented fully functional backend API for discussion forum , also clean clear information has been saved real time data fetching for better user experience
