### ISSUE TITLE
Abous Us Page is Messign Up Totally | Enhancement of Whole Page Structure

### ISSUE THREAD

**Issue by Shariq2003** [ANSHIKA-26/WordWise#412]
The about us page UI is total messing up and the whole structure of the page is disturbing, making a bad UI and UX.

https://github.com/user-attachments/assets/28da299d-641b-4fc0-9a28-05d673e6e00e

I want to restructure the whole About Us webpage including the structuring and styling.

@ANSHIKA-26 please assign this issue to me.

**Comment by Shariq2003** [comment]
@ANSHIKA-26 i don't know why the bot is closing this issue, upon checking I have found that there is no such issue existed at all.
Please review and assign this to me.

**Comment by ANSHIKA-26** [comment]
well , issue #278 does cover this , hence the bot was closing , you can ask to get assigned on that issue , it might be problematic if both of you make a PR for the same issue , both the issues are related to about us section/ page !

**Comment by Shariq2003** [comment]
> well , issue #278 does cover this , hence the bot was closing , you can ask to get assigned on that issue , it might be problematic if both of you make a PR for the same issue , both the issues are related to about us section/ page !

okay

**Comment by ANSHIKA-26** [comment]
issue 278 -On clicking the about button in navbar the page refreshes to Home again
Wanted to work on about such that on clicking about the screen scrolls down to about section in the page
Also the image in the about section overlaps the text written.


after this issue was made , a lot of Prs got merged , which messed the section further more , hence the issue doesnt cover what all they wish to change , but the fact that both of you will work on the same piece of code and then ask to merge their own PR's is what we are trying to avoid here !
