### ISSUE TITLE
Adding Custom Cursor effect 

### ISSUE THREAD

**Issue by ShrishtiSingh26** [ANSHIKA-26/WordWise#417]
### Unique cursor designs can capture users' attention and make the interaction, encouraging them to engage more with your content.

Please assign this to me , I am ready for this under Hacktoberfest and GSSOC extd
Thankyou!

**Comment by AnujShrivastava01** [comment]
@ANSHIKA-26 
This issue is still not implemented.
I want to work on this please assign this to me and give me a level3 label as I will implement this for each sub-page and ensure its responsiveness also.
I will add custom cursor to make our website more User interactive and responsive
# Demo : 
# Light Mode 
https://github.com/user-attachments/assets/e4b9c981-39da-459e-b2e9-62f81798bf9d

# Dark Mode 
https://github.com/user-attachments/assets/b233ca67-489c-4003-9d9f-08250e8b5d76
